apiVersion: v1
kind: ServiceAccount
metadata:
  name: somatic-api-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: somatic-api-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: somatic-api-binding
subjects:
  - kind: ServiceAccount
    name: somatic-api-sa
    namespace: argo
roleRef:
  kind: ClusterRole
  name: somatic-api-role
  apiGroup: rbac.authorization.k8s.io
